# Generated by Django 5.2.9 on 2026-01-18 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0003_remove_exercisesession_playlist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('CURRICULUM', '커리큘럼'), ('MANUAL', '매뉴얼')], max_length=20, verbose_name='모드')),
                ('exercise_name', models.CharField(blank=True, help_text='운동 또는 플레이리스트 이름', max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시간')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('duration', models.DurationField(blank=True, help_text='운동 지속 시간', null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='소요 시간(ms)')),
                ('is_valid', models.BooleanField(default=True, verbose_name='유효 여부')),
                ('status', models.CharField(choices=[('IN_PROGRESS', '진행 중'), ('COMPLETED', '완료됨'), ('ABORTED', '중단됨')], default='IN_PROGRESS', max_length=20, verbose_name='상태')),
                ('abnormal_end_reason', models.CharField(blank=True, choices=[('NORMAL', '정상 종료'), ('APP_KILLED', '앱 종료됨'), ('CRASH', '충돌'), ('UNKNOWN', '알 수 없음')], max_length=20, null=True, verbose_name='비정상 종료 사유')),
                ('device_id_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='디바이스 해시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='exercises.playlist', verbose_name='플레이리스트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '운동 세션',
                'verbose_name_plural': '운동 세션 목록',
                'db_table': 'exercise_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLogObject',
            fields=[
                ('log_object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=512, unique=True, verbose_name='S3 키')),
                ('content_type', models.CharField(max_length=20, verbose_name='컨텐츠 타입')),
                ('bytes', models.BigIntegerField(blank=True, null=True, verbose_name='크기(Bytes)')),
                ('checksum', models.CharField(blank=True, max_length=64, null=True, verbose_name='체크섬')),
                ('upload_status', models.CharField(choices=[('PENDING', '대기 중'), ('UPLOADED', '업로드 완료'), ('FAILED', '실패')], default='PENDING', max_length=20, verbose_name='업로드 상태')),
                ('retry_count', models.IntegerField(default=0, verbose_name='재시도 횟수')),
                ('last_error_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='최근 에러 코드')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 에러 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='업로드 일시')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log_object', to='logs.exercisesession', verbose_name='세션')),
            ],
            options={
                'verbose_name': '운동 로그 객체',
                'verbose_name_plural': '운동 로그 객체 목록',
                'db_table': 'exercise_log_objects',
            },
        ),
        migrations.CreateModel(
            name='ExerciseSessionItem',
            fields=[
                ('session_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_no', models.IntegerField(verbose_name='순서')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='소요 시간(ms)')),
                ('is_skipped', models.BooleanField(default=False, verbose_name='스킵 여부')),
                ('skip_reason', models.CharField(blank=True, choices=[('LOAD_FAIL', '로드 실패'), ('USER_SKIP', '사용자 스킵'), ('UNKNOWN', '알 수 없음')], max_length=20, null=True, verbose_name='스킵 사유')),
                ('rest_sec', models.IntegerField(default=10, verbose_name='휴식 시간(초)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='exercises.exercise', verbose_name='운동')),
                ('playlist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.playlistitem', verbose_name='플레이리스트 항목')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logs.exercisesession', verbose_name='세션')),
            ],
            options={
                'verbose_name': '세션 운동 항목',
                'verbose_name_plural': '세션 운동 항목 목록',
                'db_table': 'exercise_session_items',
            },
        ),
        migrations.CreateModel(
            name='ExerciseSessionEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_time_ms', models.BigIntegerField(verbose_name='이벤트 발생 시간(세션 시작 후 ms)')),
                ('event_type', models.CharField(max_length=50, verbose_name='이벤트 타입')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='페이로드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logs.exercisesession', verbose_name='세션')),
                ('session_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logs.exercisesessionitem', verbose_name='세션 항목')),
            ],
            options={
                'verbose_name': '세션 이벤트',
                'verbose_name_plural': '세션 이벤트 목록',
                'db_table': 'exercise_session_events',
            },
        ),
        migrations.AddIndex(
            model_name='exercisesession',
            index=models.Index(fields=['user', 'started_at'], name='exercise_se_user_id_b51cce_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciselogobject',
            index=models.Index(fields=['upload_status'], name='exercise_lo_upload__3643f5_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesessionitem',
            index=models.Index(fields=['session', 'sequence_no'], name='exercise_se_session_44ad39_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesessionevent',
            index=models.Index(fields=['session', 'event_time_ms'], name='exercise_se_session_daf887_idx'),
        ),
    ]
