# Generated by Django 5.2.9 on 2026-01-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesession',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='소요 시간(초, 소수점)'),
        ),
        migrations.AddField(
            model_name='exercisesession',
            name='last_ping_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 핑 시간'),
        ),
    ]
