# Generated by Django 5.2.4 on 2026-01-15 23:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='이름')),
                ('phone_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='전화번호')),
                ('pin_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='PIN 해시')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성'), ('U', '미선택')], max_length=1, null=True, verbose_name='성별')),
                ('height_cm', models.IntegerField(blank=True, null=True, verbose_name='키(cm)')),
                ('weight_kg', models.IntegerField(blank=True, null=True, verbose_name='몸무게(kg)')),
                ('is_profile_completed', models.BooleanField(default=False, verbose_name='프로필 완성 여부')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthProvider',
            fields=[
                ('auth_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('LOCAL', '로컬'), ('GOOGLE', '구글'), ('KAKAO', '카카오')], max_length=20, verbose_name='인증 제공자')),
                ('provider_subject', models.CharField(max_length=255, verbose_name='제공자 식별자')),
                ('provider_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='제공자 이메일')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='연동 일시')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 로그인 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_providers', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 인증 제공자',
                'verbose_name_plural': '사용자 인증 제공자 목록',
                'db_table': 'user_auth_provider',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='users_date_jo_0c802f_idx'),
        ),
        migrations.AddIndex(
            model_name='userauthprovider',
            index=models.Index(fields=['user'], name='user_auth_p_user_id_7f3cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='userauthprovider',
            index=models.Index(fields=['provider', 'provider_subject'], name='user_auth_p_provide_ad1bf8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userauthprovider',
            unique_together={('user', 'provider')},
        ),
    ]
