# Generated by Django 5.2.4 on 2026-01-15 23:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('category_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='카테고리 ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='표시 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '운동 카테고리',
                'verbose_name_plural': '운동 카테고리 목록',
                'db_table': 'exercise_category',
            },
        ),
        migrations.CreateModel(
            name='ExerciseLogObject',
            fields=[
                ('log_object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=512, unique=True, verbose_name='S3 키')),
                ('content_type', models.CharField(max_length=20, verbose_name='컨텐츠 타입')),
                ('bytes', models.BigIntegerField(blank=True, null=True, verbose_name='크기(Bytes)')),
                ('checksum', models.CharField(blank=True, max_length=64, null=True, verbose_name='체크섬')),
                ('upload_status', models.CharField(choices=[('PENDING', '대기 중'), ('UPLOADED', '업로드 완료'), ('FAILED', '실패')], default='PENDING', max_length=20, verbose_name='업로드 상태')),
                ('retry_count', models.IntegerField(default=0, verbose_name='재시도 횟수')),
                ('last_error_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='최근 에러 코드')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 에러 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='업로드 일시')),
            ],
            options={
                'verbose_name': '운동 로그 객체',
                'verbose_name_plural': '운동 로그 객체 목록',
                'db_table': 'exercise_log_objects',
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('CURRICULUM', '커리큘럼'), ('MANUAL', '매뉴얼')], max_length=20, verbose_name='모드')),
                ('started_at', models.DateTimeField(verbose_name='시작 시간')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='소요 시간(ms)')),
                ('is_valid', models.BooleanField(default=True, verbose_name='유효 여부')),
                ('abnormal_end_reason', models.CharField(blank=True, choices=[('NORMAL', '정상 종료'), ('APP_KILLED', '앱 종료됨'), ('CRASH', '충돌'), ('UNKNOWN', '알 수 없음')], max_length=20, null=True, verbose_name='비정상 종료 사유')),
                ('device_id_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='디바이스 해시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '운동 세션',
                'verbose_name_plural': '운동 세션 목록',
                'db_table': 'exercise_sessions',
            },
        ),
        migrations.CreateModel(
            name='ExerciseSessionEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_time_ms', models.BigIntegerField(verbose_name='이벤트 발생 시간(세션 시작 후 ms)')),
                ('event_type', models.CharField(max_length=50, verbose_name='이벤트 타입')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='페이로드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '세션 이벤트',
                'verbose_name_plural': '세션 이벤트 목록',
                'db_table': 'exercise_session_events',
            },
        ),
        migrations.CreateModel(
            name='ExerciseSessionItem',
            fields=[
                ('session_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_no', models.IntegerField(verbose_name='순서')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='소요 시간(ms)')),
                ('is_skipped', models.BooleanField(default=False, verbose_name='스킵 여부')),
                ('skip_reason', models.CharField(blank=True, choices=[('LOAD_FAIL', '로드 실패'), ('USER_SKIP', '사용자 스킵'), ('UNKNOWN', '알 수 없음')], max_length=20, null=True, verbose_name='스킵 사유')),
                ('rest_sec', models.IntegerField(default=10, verbose_name='휴식 시간(초)')),
            ],
            options={
                'verbose_name': '세션 운동 항목',
                'verbose_name_plural': '세션 운동 항목 목록',
                'db_table': 'exercise_session_items',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('CURRICULUM', '커리큘럼'), ('MANUAL', '매뉴얼'), ('CUSTOM', '사용자 정의')], max_length=20, verbose_name='모드')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('ARCHIVED', '보관됨')], default='ACTIVE', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '플레이리스트',
                'verbose_name_plural': '플레이리스트 목록',
                'db_table': 'playlists',
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('playlist_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_no', models.IntegerField(verbose_name='순서')),
                ('set_count', models.IntegerField(verbose_name='세트 수')),
                ('reps_count', models.IntegerField(blank=True, null=True, verbose_name='회수')),
                ('duration_sec', models.IntegerField(blank=True, null=True, verbose_name='수행 시간(초)')),
                ('rest_sec', models.IntegerField(default=10, verbose_name='휴식 시간(초)')),
                ('cue_overrides', models.JSONField(blank=True, null=True, verbose_name='큐 오버라이드')),
            ],
            options={
                'verbose_name': '플레이리스트 항목',
                'verbose_name_plural': '플레이리스트 항목 목록',
                'db_table': 'playlist_items',
                'ordering': ['sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=255, verbose_name='운동명')),
                ('exercise_description', models.TextField(blank=True, null=True, verbose_name='운동 설명')),
                ('first_description', models.TextField(blank=True, null=True, verbose_name='준비 자세 설명')),
                ('main_form', models.TextField(blank=True, null=True, verbose_name='주요 동작 설명')),
                ('form_description', models.TextField(blank=True, null=True, verbose_name='동작 상세 설명')),
                ('stay_form', models.TextField(blank=True, null=True, verbose_name='유지 동작 설명')),
                ('fixed_form', models.TextField(blank=True, null=True, verbose_name='고정 동작 설명')),
                ('exercise_guide_text', models.TextField(blank=True, null=True, verbose_name='TTS 가이드 텍스트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exercisecategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '운동',
                'verbose_name_plural': '운동 목록',
                'db_table': 'exercise',
            },
        ),
        migrations.CreateModel(
            name='ExerciseMedia',
            fields=[
                ('media_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('PICTOGRAM', '픽토그램'), ('GUIDE_AUDIO', '가이드 오디오'), ('TTS_PREGEN', 'TTS 미리 생성됨')], max_length=20, verbose_name='미디어 타입')),
                ('locale', models.CharField(default='ko-KR', max_length=10, verbose_name='로케일')),
                ('s3_key', models.CharField(blank=True, max_length=512, null=True, verbose_name='S3 키')),
                ('url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='재생 시간(ms)')),
                ('checksum', models.CharField(blank=True, max_length=64, null=True, verbose_name='체크섬')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_contents', to='exercises.exercise', verbose_name='운동')),
            ],
            options={
                'verbose_name': '운동 미디어',
                'verbose_name_plural': '운동 미디어 목록',
                'db_table': 'exercise_media',
            },
        ),
    ]
