# Generated by Django 5.2.4 on 2026-01-15 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='exerciselogobject',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log_object', to='exercises.exercisesession', verbose_name='세션'),
        ),
        migrations.AddField(
            model_name='exercisesessionevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='exercises.exercisesession', verbose_name='세션'),
        ),
        migrations.AddField(
            model_name='exercisesessionitem',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='exercises.exercise', verbose_name='운동'),
        ),
        migrations.AddField(
            model_name='exercisesessionitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exercises.exercisesession', verbose_name='세션'),
        ),
        migrations.AddField(
            model_name='exercisesessionevent',
            name='session_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='exercises.exercisesessionitem', verbose_name='세션 항목'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='exercisesession',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='exercises.playlist', verbose_name='플레이리스트'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='exercises.exercise', verbose_name='운동'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exercises.playlist', verbose_name='플레이리스트'),
        ),
        migrations.AddField(
            model_name='exercisesessionitem',
            name='playlist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.playlistitem', verbose_name='플레이리스트 항목'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['category'], name='exercise_categor_12f454_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['is_active'], name='exercise_is_acti_89e48d_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['exercise_name'], name='exercise_exercis_046ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisemedia',
            index=models.Index(fields=['exercise', 'media_type', 'locale'], name='exercise_me_exercis_5c82b5_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciselogobject',
            index=models.Index(fields=['upload_status'], name='exercise_lo_upload__3643f5_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesessionevent',
            index=models.Index(fields=['session', 'event_time_ms'], name='exercise_se_session_daf887_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', 'status'], name='playlists_user_id_1b2bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesession',
            index=models.Index(fields=['user', 'started_at'], name='exercise_se_user_id_b51cce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together={('playlist', 'sequence_no')},
        ),
        migrations.AddIndex(
            model_name='exercisesessionitem',
            index=models.Index(fields=['session', 'sequence_no'], name='exercise_se_session_44ad39_idx'),
        ),
    ]
