# Generated by Django 5.2.9 on 2026-01-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseSessionEvent',
        ),
        migrations.DeleteModel(
            name='ExerciseSessionItem',
        ),
        migrations.DeleteModel(
            name='ExerciseLogObject',
        ),
        migrations.DeleteModel(
            name='ExerciseSession',
        ),
    ]
