# Generated by Django 5.2.9 on 2026-01-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_exercisesession_playlist_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exercisemedia',
            name='exercise_me_exercis_5c82b5_idx',
        ),
        migrations.RemoveField(
            model_name='exercisemedia',
            name='locale',
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='영문명'),
        ),
        migrations.AddField(
            model_name='exercisemedia',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='순서'),
        ),
        migrations.AddIndex(
            model_name='exercisemedia',
            index=models.Index(fields=['exercise', 'media_type', 'sequence'], name='exercise_me_exercis_33cb3a_idx'),
        ),
    ]
