# Generated by Django 5.2.4 on 2026-01-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='카테고리 코드')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name': '운동 카테고리',
                'verbose_name_plural': '운동 카테고리 목록',
                'db_table': 'exercise_categories',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='운동명')),
                ('difficulty', models.CharField(choices=[('Easy', '쉬움'), ('Medium', '보통'), ('Hard', '어려움')], max_length=10, verbose_name='난이도')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exercisecategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '운동',
                'verbose_name_plural': '운동 목록',
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='순서')),
                ('script', models.TextField(verbose_name='스크립트 (TTS)')),
                ('type', models.CharField(choices=[('TTS', '음성 가이드'), ('VUI', 'VUI 가이드')], default='TTS', max_length=10, verbose_name='가이드 타입')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='exercises.exercise', verbose_name='운동')),
            ],
            options={
                'verbose_name': '운동 단계',
                'verbose_name_plural': '운동 단계 목록',
                'db_table': 'exercise_steps',
                'ordering': ['sequence'],
            },
        ),
    ]
