# Generated by Django 5.2.4 on 2026-01-07 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(verbose_name='종료 시간')),
                ('duration', models.IntegerField(verbose_name='소요 시간 (초)')),
                ('count', models.IntegerField(default=0, verbose_name='횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exercises.exercise', verbose_name='운동')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '운동 기록',
                'verbose_name_plural': '운동 기록 목록',
                'db_table': 'exercise_logs',
                'ordering': ['-start_time'],
            },
        ),
    ]
